version: '4'                 

services:
  postgres:
    container_name: pg_db
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=TestUser
      - POSTGRES_PASSWORD=TestPassword
      - POSTGRES_DB=Test_db
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "my@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "TestPassword"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"

